### ISSUE TITLE
Neural network training

### ISSUE THREAD

**Issue by nstfk** [rueycheng/QA_ExtFeats#1]
Hi,
Is the feature extraction code available yet? and also the CNN configuration

**Comment by rueycheng** [comment]
Hi there,

Thanks for the reminder. Yes, the code is available and currently under testing. I rewrote the core pipeline in python 3 during the weekend - it should be available in a few days.

Can you be more specific on what details about CNN you want to know (if they are not already mentioned in the paper)?

**Comment by nstfk** [comment]
hey again,
Thank you for the update, I was trying to reproduce the results and got confused on how to feed the features to the connected layer of the CNN. Also the word overlap features were fed to the convolution layer instead?

**Comment by rueycheng** [comment]
Short answer is: These details can be found in Severyn and Moschitti (2015). We used their code to implement our experiments so it might be worthwhile to read their paper first.

Also, in case this is still not clear to you I dropped in some model training scripts and instructions in this repo just now. Hope this helps.

**Comment by nstfk** [comment]
Great thanks
